use bevy::prelude::*;
use derive_more::From;
use num_enum::{IntoPrimitive, TryFromPrimitive};
use strum::{Display, EnumIter};

#[derive(Clone, Copy, Debug, From, PartialEq, Reflect)]
pub enum ActionId {
    Core(CoreAction),
    Advanced(AdvancedAction),
    Special(SpecialAction),
}

impl From<ActionId> for u32 {
    fn from(id: ActionId) -> Self {
        match id {
            ActionId::Core(id) => id.into(),
            ActionId::Advanced(id) => id.into(),
            ActionId::Special(id) => id.into(),
        }
    }
}

impl From<ActionId> for i32 {
    fn from(id: ActionId) -> Self {
        match id {
            ActionId::Core(id) => u32::from(id) as i32,
            ActionId::Advanced(id) => u32::from(id) as i32,
            ActionId::Special(id) => u32::from(id) as i32,
        }
    }
}

impl TryFrom<u32> for ActionId {
    type Error = &'static str;

    fn try_from(value: u32) -> Result<Self, Self::Error> {
        if let Ok(action) = CoreAction::try_from(value) {
            return Ok(ActionId::Core(action));
        }
        if let Ok(action) = AdvancedAction::try_from(value) {
            return Ok(ActionId::Advanced(action));
        }
        if let Ok(action) = SpecialAction::try_from(value) {
            return Ok(ActionId::Special(action));
        }

        Err("Invalid ActionId")
    }
}

pub const DEFAULT_ACTIONS: [u32; 43] = [
    CoreAction::SitStand as u32,
    CoreAction::WalkRun as u32,
    CoreAction::Attack as u32,
    CoreAction::Exchange as u32,
    CoreAction::NextTarget as u32,
    CoreAction::PickUp as u32,
    CoreAction::Assist as u32,
    CoreAction::PrivateStoreSell as u32,
    CoreAction::PrivateStoreBuy as u32,
    CoreAction::Recommend as u32,
    CoreAction::GeneralManufacture as u32,
    CoreAction::StartEndRecordingReplay as u32,
    CoreAction::FindStore as u32,
    CoreAction::Duel as u32,
    CoreAction::Withdraw as u32,
    CoreAction::PrivateStorePackageSell as u32,
    CoreAction::MiniGame as u32,
    CoreAction::MyTeleports as u32,
    CoreAction::BotReportButton as u32,
    CoreAction::Invite as u32,
    CoreAction::LeaveParty as u32,
    CoreAction::DismissPartyMember as u32,
    CoreAction::PartyMatching as u32,
    CoreAction::ChangeOfPartyLeader as u32,
    CoreAction::CommandChannelInvitation as u32,
    CoreAction::PartyDuel as u32,
    CoreAction::Greeting as u32,
    CoreAction::Victory as u32,
    CoreAction::Advance as u32,
    CoreAction::Yes as u32,
    CoreAction::No as u32,
    CoreAction::Bow as u32,
    CoreAction::Unaware as u32,
    CoreAction::SocialWaiting as u32,
    CoreAction::Laugh as u32,
    CoreAction::Applaud as u32,
    CoreAction::Dance as u32,
    CoreAction::Sorrow as u32,
    CoreAction::Charm as u32,
    CoreAction::Shyness as u32,
    CoreAction::ExchangeBows as u32,
    CoreAction::HighFive as u32,
    CoreAction::CoupleDance as u32,
];

pub const ACTIONS_ON_TRANSFORM: [u32; 135] = [
    CoreAction::WalkRun as u32,
    CoreAction::Attack as u32,
    CoreAction::Exchange as u32,
    CoreAction::NextTarget as u32,
    CoreAction::PickUp as u32,
    CoreAction::Assist as u32,
    CoreAction::Invite as u32,
    CoreAction::LeaveParty as u32,
    CoreAction::DismissPartyMember as u32,
    CoreAction::PartyMatching as u32,
    CoreAction::ChangeMovementMode as u32,
    CoreAction::Attack2 as u32,
    CoreAction::Stop as u32,
    CoreAction::Pickup2 as u32,
    CoreAction::UnsummonPet as u32,
    CoreAction::ChangeMovementModePets as u32,
    CoreAction::AttackPets as u32,
    CoreAction::StopPets as u32,
    CoreAction::SwitchMode as u32,
    CoreAction::ToxicSmoke as u32,
    CoreAction::ParasiteBurst as u32,
    CoreAction::Recommend as u32,
    CoreAction::WildHogCannonAttack as u32,
    CoreAction::SelfDamageShield as u32,
    CoreAction::HydroScrew as u32,
    CoreAction::BoomAttack as u32,
    CoreAction::MasterRecharge as u32,
    CoreAction::MegaStormStrike as u32,
    CoreAction::StealBlood as u32,
    CoreAction::MechCannon as u32,
    CoreAction::ChangeOfPartyLeader as u32,
    CoreAction::UnsummonServitor as u32,
    CoreAction::MoveToTargetServitors as u32,
    CoreAction::MoveToTargetPets as u32,
    CoreAction::StartEndRecordingReplay as u32,
    CoreAction::CommandChannelInvitation as u32,
    CoreAction::FindStore as u32,
    CoreAction::MiniGame as u32,
    CoreAction::MyTeleports as u32,
    CoreAction::BotReportButton as u32,
    CoreAction::ExitAirship as u32,
    // TODO: Not shure that we need all this AdvancedAction, possibly it should be filtered by tranform
    AdvancedAction::SiegeGolemSiegeHammer as u32,
    AdvancedAction::SinEaterUltimateBombasticBuster as u32,
    AdvancedAction::WindHatchlingStriderWildStun as u32,
    AdvancedAction::WindHatchlingStriderWildDefence as u32,
    AdvancedAction::StarHatchlingStriderBrightBurst as u32,
    AdvancedAction::StarHatchlingStriderBrightHeal as u32,
    AdvancedAction::FelineQueenBlessingOfQueen as u32,
    AdvancedAction::FelineQueenGiftOfQueen as u32,
    AdvancedAction::FelineQueenCureOfQueen as u32,
    AdvancedAction::UnicornSeraphimBlessingOfSeraphim as u32,
    AdvancedAction::UnicornSeraphimGiftOfSeraphim as u32,
    AdvancedAction::UnicornSeraphimCureOfSeraphim as u32,
    AdvancedAction::NightshadeCurseOfShade as u32,
    AdvancedAction::NightshadeMassCurseOfShade as u32,
    AdvancedAction::NightshadeShadeSacrifice as u32,
    AdvancedAction::CursedManCursedBlow as u32,
    AdvancedAction::CursedManCursedStun as u32,
    AdvancedAction::CursedManCursedDrainEnergy as u32,
    AdvancedAction::KatTheCatSkill2 as u32,
    AdvancedAction::MewTheCatSkill2 as u32,
    AdvancedAction::KaiTheCatSkill2 as u32,
    AdvancedAction::BoxerTheUnicornSkill2 as u32,
    AdvancedAction::MirageTheUnicornSkill2 as u32,
    AdvancedAction::MerrowTheUnicornSkill2 as u32,
    AdvancedAction::ShadowSkill1 as u32,
    AdvancedAction::ShadowSkill2 as u32,
    AdvancedAction::SilhouetteSkill2 as u32,
    AdvancedAction::ReanimatedManSkill1 as u32,
    AdvancedAction::ReanimatedManSkill2 as u32,
    AdvancedAction::CorruptedManSkill2 as u32,
    AdvancedAction::FelineKingSlash as u32,
    AdvancedAction::FelineKingSpinningSlash as u32,
    AdvancedAction::FelineKingHoldOfKing as u32,
    AdvancedAction::MagnusTheUnicornWhiplash as u32,
    AdvancedAction::MagnusTheUnicornTidalWave as u32,
    AdvancedAction::SpectralLordCorpseKaboom as u32,
    AdvancedAction::SpectralLordDicingDeath as u32,
    AdvancedAction::SpectralLordDarkCurse as u32,
    AdvancedAction::SwoopCannonCannonFodder as u32,
    AdvancedAction::SwoopCannonBigBang as u32,
    AdvancedAction::GreatWolfBiteAttack as u32,
    AdvancedAction::GreatWolfMaul as u32,
    AdvancedAction::GreatWolfCryOfTheWolf as u32,
    AdvancedAction::GreatWolfAwakening as u32,
    AdvancedAction::GreatWolfHowl as u32,
    AdvancedAction::StriderRoar as u32,
    AdvancedAction::DivineBeastBite as u32,
    AdvancedAction::DivineBeastStunAttack as u32,
    AdvancedAction::DivineBeastFireBreath as u32,
    AdvancedAction::DivineBeastRoar as u32,
    AdvancedAction::FelineQueenBlessTheBody as u32,
    AdvancedAction::FelineQueenBlessTheSoul as u32,
    AdvancedAction::FelineQueenHaste as u32,
    AdvancedAction::UnicornSeraphimAcumen as u32,
    AdvancedAction::UnicornSeraphimClarity as u32,
    AdvancedAction::UnicornSeraphimEmpower as u32,
    AdvancedAction::UnicornSeraphimWildMagic as u32,
    AdvancedAction::NightshadeDeathWhisper as u32,
    AdvancedAction::NightshadeFocus as u32,
    AdvancedAction::NightshadeGuidance as u32,
    AdvancedAction::WildBeastFighterDeathBlow as u32,
    AdvancedAction::WildBeastFighterDoubleAttack as u32,
    AdvancedAction::WildBeastFighterSpinAttack as u32,
    AdvancedAction::WildBeastFighterMeteorShower as u32,
    AdvancedAction::FoxShamanFairyPrincessAwakening as u32,
    AdvancedAction::FoxShamanSpiritShamanThunderBolt as u32,
    AdvancedAction::FoxShamanSpiritShamanFlash as u32,
    AdvancedAction::FoxShamanSpiritShamanLightningWave as u32,
    AdvancedAction::FoxShamanFairyPrincessFlare as u32,
    AdvancedAction::WhiteWeaselFairyPrincessImprovedPetsBuffControl as u32,
    AdvancedAction::TigressPowerStrike as u32,
    AdvancedAction::ToyKnightPiercingAttack as u32,
    AdvancedAction::ToyKnightWhirlwind as u32,
    AdvancedAction::ToyKnightLanceSmash as u32,
    AdvancedAction::ToyKnightBattleCry as u32,
    AdvancedAction::TurtleAsceticPowerSmash as u32,
    AdvancedAction::TurtleAsceticEnergyBurst as u32,
    AdvancedAction::TurtleAsceticShockwave as u32,
    AdvancedAction::TurtleAsceticHowl as u32,
    AdvancedAction::PhoenixRush as u32,
    AdvancedAction::PhoenixCleanse as u32,
    AdvancedAction::PhoenixFlameFeather as u32,
    AdvancedAction::PhoenixFlameBeak as u32,
    AdvancedAction::SwitchState as u32,
    AdvancedAction::DeinonychusTailStrike as u32,
    AdvancedAction::GuardiansStriderStriderBite as u32,
    AdvancedAction::GuardiansStriderStriderFear as u32,
    AdvancedAction::GuardiansStriderStriderDash as u32,
    AdvancedAction::MaguenStrike as u32,
    AdvancedAction::MaguenWindWalk as u32,
    AdvancedAction::EliteMaguenPowerStrike as u32,
    AdvancedAction::EliteMaguenWindWalk as u32,
    AdvancedAction::MaguenReturn as u32,
    AdvancedAction::EliteMaguenPartyReturn as u32,
];

#[derive(
    EnumIter,
    Display,
    Default,
    Copy,
    Event,
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    TryFromPrimitive,
    IntoPrimitive,
    Reflect,
)]
#[repr(u32)]
pub enum CoreAction {
    #[default]
    SitStand = 0,
    WalkRun,
    Attack,
    Exchange,
    NextTarget,
    PickUp,
    Assist,
    Invite,
    LeaveParty,
    DismissPartyMember,
    PrivateStoreSell,
    PartyMatching,
    Greeting,
    Victory,
    Advance,
    ChangeMovementMode,
    Attack2,
    Stop,
    Pickup2,
    UnsummonPet,
    SpecialSkill1,
    ChangeMovementModePets,
    AttackPets,
    StopPets,
    Yes,
    No,
    Bow,
    SpecialSkill2,
    PrivateStoreBuy,
    Unaware,
    SocialWaiting,
    Laugh,
    SwitchMode,
    Applaud,
    Dance,
    Sorrow,
    ToxicSmoke,
    DwarvenManufacture,
    MountDismount,
    ParasiteBurst,
    Recommend,
    WildHogCannonAttack,
    SelfDamageShield,
    HydroScrew,
    BoomAttack,
    MasterRecharge,
    MegaStormStrike,
    StealBlood,
    MechCannon,
    WildTemper,
    ChangeOfPartyLeader,
    GeneralManufacture,
    UnsummonServitor,
    MoveToTargetServitors,
    MoveToTargetPets,
    StartEndRecordingReplay,
    CommandChannelInvitation,
    FindStore,
    Duel,
    Withdraw,
    PartyDuel,
    PrivateStorePackageSell,
    Charm,
    MiniGame,
    MyTeleports,
    BotReportButton,
    Shyness,
    Steer,
    CancelControl,
    DestinationMap,
    ExitAirship,
    ExchangeBows,
    HighFive,
    CoupleDance,
}
impl From<ActionId> for CoreAction {
    fn from(id: ActionId) -> Self {
        match id {
            ActionId::Core(id) => id,
            _ => panic!("Invalid conversion"),
        }
    }
}

#[derive(
    EnumIter,
    Display,
    Copy,
    Event,
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    TryFromPrimitive,
    IntoPrimitive,
    Reflect,
)]
#[repr(u32)]
pub enum AdvancedAction {
    SiegeGolemSiegeHammer = 1000,
    SinEaterUltimateBombasticBuster,
    HostileFeeling,
    WindHatchlingStriderWildStun,
    WindHatchlingStriderWildDefence,
    StarHatchlingStriderBrightBurst,
    StarHatchlingStriderBrightHeal,
    FelineQueenBlessingOfQueen,
    FelineQueenGiftOfQueen,
    FelineQueenCureOfQueen,
    UnicornSeraphimBlessingOfSeraphim,
    UnicornSeraphimGiftOfSeraphim,
    UnicornSeraphimCureOfSeraphim,
    NightshadeCurseOfShade,
    NightshadeMassCurseOfShade,
    NightshadeShadeSacrifice,
    CursedManCursedBlow,
    CursedManCursedStun,
    CursedManCursedDrainEnergy,
    KatTheCatSkill2,
    MewTheCatSkill2,
    KaiTheCatSkill2,
    BoxerTheUnicornSkill2,
    MirageTheUnicornSkill2,
    MerrowTheUnicornSkill2,
    ShadowSkill1,
    ShadowSkill2,
    SilhouetteSkill2,
    ReanimatedManSkill1,
    ReanimatedManSkill2,
    CorruptedManSkill2,
    FelineKingSlash,
    FelineKingSpinningSlash,
    FelineKingHoldOfKing,
    MagnusTheUnicornWhiplash,
    MagnusTheUnicornTidalWave,
    SpectralLordCorpseKaboom,
    SpectralLordDicingDeath,
    SpectralLordDarkCurse,
    SwoopCannonCannonFodder,
    SwoopCannonBigBang,
    GreatWolfBiteAttack,
    GreatWolfMaul,
    GreatWolfCryOfTheWolf,
    GreatWolfAwakening,
    GreatWolfHowl,
    StriderRoar,
    DivineBeastBite,
    DivineBeastStunAttack,
    DivineBeastFireBreath,
    DivineBeastRoar,
    FelineQueenBlessTheBody,
    FelineQueenBlessTheSoul,
    FelineQueenHaste,
    UnicornSeraphimAcumen,
    UnicornSeraphimClarity,
    UnicornSeraphimEmpower,
    UnicornSeraphimWildMagic,
    NightshadeDeathWhisper,
    NightshadeFocus,
    NightshadeGuidance,
    WildBeastFighterDeathBlow,
    WildBeastFighterDoubleAttack,
    WildBeastFighterSpinAttack,
    WildBeastFighterMeteorShower,
    FoxShamanFairyPrincessAwakening,
    FoxShamanSpiritShamanThunderBolt,
    FoxShamanSpiritShamanFlash,
    FoxShamanSpiritShamanLightningWave,
    FoxShamanFairyPrincessFlare,
    WhiteWeaselFairyPrincessImprovedPetsBuffControl,
    TigressPowerStrike,
    ToyKnightPiercingAttack,
    ToyKnightWhirlwind,
    ToyKnightLanceSmash,
    ToyKnightBattleCry,
    TurtleAsceticPowerSmash,
    TurtleAsceticEnergyBurst,
    TurtleAsceticShockwave,
    TurtleAsceticHowl,
    PhoenixRush,
    PhoenixCleanse,
    PhoenixFlameFeather,
    PhoenixFlameBeak,
    SwitchState,
    Unkown1,
    PantherCancel,
    PantherDarkClaw,
    PantherFatalClaw,
    DeinonychusTailStrike,
    GuardiansStriderStriderBite,
    GuardiansStriderStriderFear,
    GuardiansStriderStriderDash,
    MaguenStrike,
    MaguenWindWalk,
    EliteMaguenPowerStrike,
    EliteMaguenWindWalk,
    MaguenReturn,
    EliteMaguenPartyReturn,
}
impl From<ActionId> for AdvancedAction {
    fn from(id: ActionId) -> Self {
        match id {
            ActionId::Advanced(id) => id,
            _ => panic!("Invalid conversion"),
        }
    }
}

#[derive(
    EnumIter,
    Display,
    Copy,
    Event,
    Debug,
    Clone,
    PartialEq,
    Eq,
    Hash,
    TryFromPrimitive,
    IntoPrimitive,
    Reflect,
)]
#[repr(u32)]
pub enum SpecialAction {
    HandOfWarmth = 5000,
    RosySeduction,
    CriticalSeduction,
    ThunderBolt,
    Flash,
    LightningWave,
    BuffControl,
    PiercingAttack,
    SpinAttack,
    Impale,
    BattleCry,
    PowerSmash,
    EnergyBurst,
    Shockwave,
    Burst,
    SwitchTactics,
    CatTheRangerBoost,
}
impl From<ActionId> for SpecialAction {
    fn from(id: ActionId) -> Self {
        match id {
            ActionId::Special(id) => id,
            _ => panic!("Invalid conversion"),
        }
    }
}
