[package]
name = "system_messages"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
l2r_core = { path = "../../../core", features = ["high_five"] }

serde = { workspace = true }
derive_more = { workspace = true }